// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using infrastructure.Data.Context;

#nullable disable

namespace infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822170201_RenameItemsToProprietarios")]
    partial class RenameItemsToProprietarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Imovel.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Proprietario.Proprietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Majoritario")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Porcentagem")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Proprietario", (string)null);
                });

            modelBuilder.Entity("ImovelProprietario", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProprietariosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImovelId", "ProprietariosId");

                    b.HasIndex("ProprietariosId");

                    b.ToTable("ImovelProprietario", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Imovel.ImovelRural", b =>
                {
                    b.HasBaseType("Domain.Models.Imovel.Imovel");

                    b.Property<decimal>("Hectares")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("ImovelRural", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Imovel.ImovelUrbano", b =>
                {
                    b.HasBaseType("Domain.Models.Imovel.Imovel");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ImovelUrbano", (string)null);
                });

            modelBuilder.Entity("ImovelProprietario", b =>
                {
                    b.HasOne("Domain.Models.Imovel.Imovel", null)
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Proprietario.Proprietario", null)
                        .WithMany()
                        .HasForeignKey("ProprietariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Imovel.ImovelRural", b =>
                {
                    b.HasOne("Domain.Models.Imovel.Imovel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Imovel.ImovelRural", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Imovel.ImovelUrbano", b =>
                {
                    b.HasOne("Domain.Models.Imovel.Imovel", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.Imovel.ImovelUrbano", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
